[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
PORT = "8000"

[[services]]
name = "pokernow-tracker-backend"
rootDirectory = "backend" 