[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"

[[services]]
name = "pokernow-tracker-backend"
rootDirectory = "backend" 