name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive .
        
    - name: Check code formatting with flake8
      run: |
        flake8 .
    
    - name: Verify backend build and run
      run: |
        # Make CI script executable
        chmod +x ci.sh
        # Run the script with a timeout of 10 seconds to verify it starts up
        timeout 10s ./ci.sh || code=$?; if [ $code -eq 124 ]; then exit 0; else exit $code; fi
      env:
        FLASK_ENV: testing
        PYTHONUNBUFFERED: 1

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Build frontend
      run: npm run build 